import type { BrandKit, JourneyStepId } from "../types";
import { NotPlanned } from "./SectionMeta";

interface Row {
  dimension: string;
  value: string | null;
  /** The journey step that fills this row when empty; rows no step fills have none. */
  step?: JourneyStepId;
}

/** Brand Persona table. Every row is either a direct read from the kit (tagged with what
 *  it actually reads from) or explicitly marked not captured -- "Differentiation" and
 *  "Strategic emotional cue" have no source anywhere in this kit, so those rows say so
 *  instead of inventing plausible-sounding values. Same discipline as the omitted
 *  market-share fact tile above.
 *
 *  "Brand role" and "Personality" used to be permanently not-captured too -- there was
 *  no field for either. brand_personification (generated by the kit-brand-persona
 *  agent, U2/U5) is exactly that field once it exists on the kit: archetype fills
 *  "Brand role", traits fill "Personality", and its narrative gets its own row. */
export function BrandPersonaTable({ kit, onOpen }: { kit: BrandKit; onOpen?: (step: JourneyStepId) => void }) {
  const bp = kit.brand_personification;
  const rows: Row[] = [
    { dimension: "Brand role", value: bp?.archetype ?? null, step: "message" },
    { dimension: "Core promise", value: kit.positioning_statement, step: "message" },
    { dimension: "Core message", value: kit.core_claim, step: "message" },
    { dimension: "Personality", value: bp?.traits?.length ? bp.traits.join(", ") : null, step: "message" },
    { dimension: "Tone", value: kit.tone_pillars.join(", "), step: "message" },
    { dimension: "Message territories", value: kit.message_hierarchy.map((m) => m.pillar).join(", "), step: "message" },
    { dimension: "If this brand were a person", value: bp?.narrative ?? null, step: "message" },
    { dimension: "Differentiation", value: null },
    { dimension: "Avoid", value: kit.guardrails.donts.slice(0, 3).map((d) => d.text).join("; "), step: "kit" },
    { dimension: "Strategic emotional cue", value: null },
  ];
  const missing = rows.filter((r) => !r.value).length;

  return (
    <div className="persona-table-wrap">
      <table className="persona-table">
        <tbody>
          {rows.map((r) => (
            <tr key={r.dimension}>
              <th>{r.dimension}</th>
              <td>
                {r.value
                  ? r.value
                  : r.step
                    ? <NotPlanned step={r.step} onOpen={onOpen} className="persona-table-missing" />
                    : <span className="persona-table-missing">Not captured in this brand kit yet</span>}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
      {missing > 0 && (
        <p className="persona-table-note">
          {missing} of {rows.length} dimensions have no source in the kit yet -- shown as missing rather than guessed.
        </p>
      )}
    </div>
  );
}
