/** Shape of `config/brand_kits.json`'s per-brand kit, as returned by
 *  GET /api/brand-kits/{brand} (strategy/brand_kit.py). Read-only for now -- the kit is
 *  still committed config, not an editable record; see idea 3/6 in the brand-workspace
 *  ideation doc for what "living" would require. */

export interface BrandSummary {
  brand: string;
  generic: string;
  company: string;
  therapy_area: string;
  indication: string;
  /** Territories this brand's kit is actually configured for -- the real gate. A brand
   *  never lists a territory here it doesn't have content for. */
  territories: string[];
}

export interface MessagePillar {
  pillar: string;
  claim: string;
  evidence: string;
}

export interface ClinicalDataPoint {
  study: string;
  stat: string;
  context: string;
}

export interface Claim {
  id: string;
  text: string;
  category: string;
  status: "draft" | "in_review" | "approved" | string;
  risk: "Low" | "Medium" | "High" | string;
  class: string;
  references: string[];
  fair_balance: string;
  note?: string;
}

export interface Reference {
  id: string;
  title: string;
  type: string;
  key_data: string;
  promo_eligible: boolean;
  note?: string;
}

export interface GuardrailEntry {
  category: string;
  text: string;
}

export interface Guardrails {
  dos: GuardrailEntry[];
  donts: GuardrailEntry[];
}

export interface IdentityColor {
  hex: string;
  name: string;
  use: string;
}

export interface Identity {
  palette: IdentityColor[];
  typography: string;
}

/** "If this brand were a person" -- generated by the kit-brand-persona agent
 *  alongside its existing tone_pillars/voice_do/voice_dont/message_hierarchy fields.
 *  Same no-fabrication discipline: absent until an ingested document actually supports
 *  it. */
export interface BrandPersonification {
  archetype: string;
  traits: string[];
  narrative: string;
}

export interface Persona {
  name: string;
  who: string;
  tier: string;
  voice: string;
  /** Marketer-depth fields -- generated by the kit-hcp-persona agent from an ingested
   *  brand-plan document, same "only what the source text supports" discipline as
   *  every other generated field in this app. All optional: a kit or a fresh diff may
   *  not have them yet. `string | string[]`: the source text sometimes supports one
   *  goal/barrier/objection, sometimes several -- the agent isn't forced to pad a
   *  single real finding into an array, or run several into one string. */
  practice_setting?: string;
  goals?: string | string[];
  barriers?: string | string[];
  channel_preference?: string;
  objections?: string | string[];
  message_resonance?: string;
  /** 2-4 sentences of marketer-style prose bio -- written from the source text, not a
   *  restatement of the structured fields above. */
  narrative?: string;
}

export interface Personas {
  hcp: Persona[];
  patient: Persona[];
  payer: Persona[];
}

export interface Concept {
  id?: string;
  name?: string;
  status: string;
  tags?: string[];
  description?: string;
}

export interface Competitor {
  name: string;
  threat: string;
  detail: string;
}

export interface Component {
  claim_links?: string[];
  [key: string]: unknown;
}

export interface MarketShare {
  current: string;
  target: string;
}

export interface BrandKit {
  source_label: string;
  source_note: string;
  company: string;
  generic: string;
  therapy_area: string;
  indication: string;
  territories: string[];
  /** Not present on every kit -- both are commercial-planning metadata this kit's source
   *  document doesn't always carry. Absent rather than guessed when the kit has neither. */
  key_objective?: string;
  market_share?: MarketShare;
  /** Journey Brief/Audience answers (plan KTD4). Optional: older kits predate them. */
  lifecycle_stage?: string;
  success_measure?: string;
  /** "branded" | "unbranded"; gates product-claim questions in the journey. */
  branded?: string;
  primary_audience?: string;
  /** Which territory this resolved kit reflects, and whether the fields shown were
   *  overridden with a hand-authored placeholder for that territory -- see
   *  strategy/brand_kit.py's resolve_territory(). When true, `note` explains it. */
  territory?: string;
  illustrative?: boolean;
  note?: string;
  /** ISO timestamp of when config/brand_kits.json was last modified -- the one real
   *  "last updated" signal that exists. Shared by every section; there is no per-section
   *  change history yet, so this is never split into a fake per-section date. */
  updated_at?: string;
  fiscal_frame: string;
  tagline: string;
  core_claim: string;
  positioning_statement: string;
  message_hierarchy: MessagePillar[];
  approved_indication: string;
  safety_reference: string;
  clinical_data: ClinicalDataPoint[];
  tone_pillars: string[];
  voice_do: string[];
  voice_dont: string[];
  brand_personification?: BrandPersonification;
  guardrails: Guardrails;
  concepts: Concept[];
  message_pool: string[];
  claims: Claim[];
  references: Reference[];
  components: Component[];
  personas: Personas;
  competitors: Competitor[];
  care_continuum: Record<string, unknown>;
  identity: Identity;
}

/* ---- Agentic Brand Journey (plan U4/U5) -- shapes returned by /api/brands/{brand}/journey ---- */

export const JOURNEY_STEPS = ["brief", "audience", "message", "kit", "flow"] as const;
export type JourneyStepId = (typeof JOURNEY_STEPS)[number];
export type JourneyStepStatus = "not_started" | "drafted" | "confirmed";

export interface JourneyDraft {
  id: string;
  step: JourneyStepId;
  field: string;
  /** "set" replaces the field; "append" adds `value` as one item (to sub-list `path` if set). */
  mode: "set" | "append" | string;
  path: string | null;
  value: unknown;
  created_at: string;
}

export interface JourneyQuestion {
  step: JourneyStepId;
  key: string;
  target: string;
  question: string;
  chips: string[];
  required: boolean;
}

export interface JourneyTurnNote {
  role: string;
  text: string;
  created_at: string;
}

export interface JourneyStep {
  step: JourneyStepId;
  label: string;
  status: JourneyStepStatus;
  waiting: JourneyStepId[];
  drafts: JourneyDraft[];
  question: JourneyQuestion | null;
  earlier_count: number;
  /** Required fields with no kept value; the step can't be confirmed until this is empty. */
  missing: string[];
  history?: JourneyTurnNote[];
}

export interface JourneyState {
  brand: string;
  steps: JourneyStep[];
}

export interface JourneyTurnResult {
  reply: string;
  question: JourneyQuestion | null;
  drafts: JourneyDraft[];
  dropped: string[];
  mode: "llm" | "fallback";
  state: JourneyState;
}

export interface JourneyFlowNode {
  id: string;
  type: string;
  position?: { x: number; y: number };
  data: { label: string; day?: number | string; channel?: string; detail?: string; block_code?: string };
}

export interface JourneyFlow {
  brand: string;
  status: "waiting" | "not_built" | "built";
  waiting: JourneyStepId[];
  flow: JourneyCampaignFlow | null;
  /** Kept structured edits, reapplied on every rebuild (KTD8). */
  ops: JourneyFlowOp[];
  /** Kept edits a rebuild could not reapply, with the reason. */
  dropped: { op: JourneyFlowOp; reason: string }[];
  /** Pending chat edit: its ops and the flow they would produce. */
  draft: { ops: JourneyFlowOp[]; flow: JourneyCampaignFlow } | null;
}

export interface JourneyFlowEdge { id: string; source: string; target: string; label?: string }
export interface JourneyCampaignFlow { nodes: JourneyFlowNode[]; edges: JourneyFlowEdge[] }

/** Structured flow edit (R17): the only way chat changes the flow. */
export type JourneyFlowOp =
  | { op: "add"; type: string; label: string; after?: string; channel?: string; detail?: string; day?: number }
  | { op: "remove"; code: string }
  | { op: "connect"; from: string; to: string; label?: string }
  | { op: "change"; code: string; set: { label?: string; channel?: string; detail?: string; day?: number } };

export interface JourneyFlowTurnResult { reply: string; mode: "ops" | "llm" | "fallback"; flow: JourneyFlow }
