"""Re-shape the committed HCP 360 target list so segment sizes actually differ.

The panel was generated by cycling a segment list, so all six segments landed within a
third of a point of each other (~19.9% each). That makes the sizing meaningless: "the
largest addressable segment" came down to rounding noise, and every segment in the planning
ask looked equally worth leading with.

This rewrites only `segment__c` in config/hcp_360/tbl_tl_data__dlm.json, to the pyramid in
strategy/segment_labels.SEGMENT_MIX. Every other column is untouched, and the assignment is
deterministic, so re-running produces the same panel.

    python scripts/rebalance_hcp_segments.py [--dry-run]

Reload the database afterwards (the app does this on boot, or force it directly):

    python -c "import sys; sys.path.insert(0,'strategy'); import hcp_360; hcp_360.load_hcp_360(force=True)"
"""
from __future__ import annotations

import collections
import json
import pathlib
import sys

BASE_DIR = pathlib.Path(__file__).resolve().parent.parent
CONFIG_DIR = BASE_DIR / "config" / "hcp_360"
sys.path.insert(0, str(BASE_DIR / "strategy"))
import segment_labels  # noqa: E402

TARGET_LIST = CONFIG_DIR / "tbl_tl_data__dlm.json"


def _report(title: str, rows: list[dict]) -> None:
    counts = collections.Counter(row.get("segment__c") for row in rows if row.get("segment__c"))
    total = sum(counts.values()) or 1
    print(f"\n{title}")
    for name, count in counts.most_common():
        print(f"  {segment_labels.to_display(name):<32} {count:>5}  {100 * count / total:5.1f}%")


def main() -> None:
    dry_run = "--dry-run" in sys.argv
    rows = json.loads(TARGET_LIST.read_text(encoding="utf-8"))
    _report(f"before ({len(rows)} rows)", rows)

    # Sort by NPI first so the assignment does not depend on file order -- two runs against
    # the same panel must produce the same segment per HCP.
    order = sorted(range(len(rows)), key=lambda i: str(rows[i].get("npi_id__c", "")))
    assignment = segment_labels.assign_segments(len(order))
    for position, row_index in enumerate(order):
        rows[row_index]["segment__c"] = assignment[position]

    _report("after", rows)
    if dry_run:
        print("\n--dry-run: nothing written")
        return
    TARGET_LIST.write_text(json.dumps(rows, indent=2) + "\n", encoding="utf-8")
    print(f"\nwrote {TARGET_LIST.relative_to(BASE_DIR)}")


if __name__ == "__main__":
    main()
